-- AlterTable
ALTER TABLE "Athlete" ADD COLUMN "gender" TEXT;
ALTER TABLE "Athlete" ADD COLUMN "dateOfBirth" TIMESTAMP(3);
ALTER TABLE "Athlete" ADD COLUMN "heightCm" DOUBLE PRECISION;
ALTER TABLE "Athlete" ADD COLUMN "weightKg" DOUBLE PRECISION;
ALTER TABLE "Athlete" ADD COLUMN "armSpanCm" DOUBLE PRECISION;
ALTER TABLE "Athlete" ADD COLUMN "sittingHeightCm" DOUBLE PRECISION;
ALTER TABLE "Athlete" ADD COLUMN "bodyFatPercent" DOUBLE PRECISION;
ALTER TABLE "Athlete" ADD COLUMN "restingHeartRate" INTEGER;
